import type { Component } from 'vue'
import {
  ElCard,
  ElForm,
  ElFormItem,
  ElInput,
  ElButton,
  ElTable,
  ElTableColumn,
  ElSelect,
  ElOption,
  ElSwitch,
  ElRadioGroup,
  ElCheckboxGroup,
  ElDatePicker,
  ElTimePicker,
  ElInputNumber,
  ElRate,
  ElSlider,
  ElColorPicker,
  ElUpload,
  ElTag,
  ElCollapse,
  ElCollapseItem,
  ElTabs,
  ElTabPane,
  ElAlert,
  ElDialog,
  ElDivider,
  ElImage,
  ElLink,
  ElSpace,
  ElRow,
  ElCol,
  ElDescriptions,
  ElDescriptionsItem,
  ElTimeline,
  ElTimelineItem,
  ElSteps,
  ElStep,
  ElProgress,
  ElBadge,
  ElAvatar,
  ElTooltip,
  ElPopover,
  ElDrawer,
  ElResult,
  ElEmpty,
  ElScrollbar,
} from 'element-plus'

export const customComponents: Record<string, Component> = {
  Page: ElCard,
  Text: 'div' as unknown as Component,
  TinyForm: ElForm,
  TinyFormItem: ElFormItem,
  TinyInput: ElInput,
  TinyButton: ElButton,
  TinySelect: ElSelect,
  TinyOption: ElOption,
  TinySwitch: ElSwitch,
  TinyRadio: ElRadioGroup,
  TinyCheckbox: ElCheckboxGroup,
  TinyDatePicker: ElDatePicker,
  TinyTimePicker: ElTimePicker,
  TinyNumeric: ElInputNumber,
  TinyRate: ElRate,
  TinySlider: ElSlider,
  TinyColorPicker: ElColorPicker,
  TinyUpload: ElUpload,
  TinyTag: ElTag,
  TinyCard: ElCard,
  TinyCollapse: ElCollapse,
  TinyCollapseItem: ElCollapseItem,
  TinyTabs: ElTabs,
  TinyTabPane: ElTabPane,
  TinyAlert: ElAlert,
  TinyDivider: ElDivider,
  TinyImage: ElImage,
  TinyLink: ElLink,
  TinySpace: ElSpace,
  TinyRow: ElRow,
  TinyCol: ElCol,
  TinyTable: ElTable,
  TinyTableColumn: ElTableColumn,
  TinyDescriptions: ElDescriptions,
  TinyDescriptionsItem: ElDescriptionsItem,
  TinyTimeline: ElTimeline,
  TinyTimelineItem: ElTimelineItem,
  TinySteps: ElSteps,
  TinyStep: ElStep,
  TinyProgress: ElProgress,
  TinyBadge: ElBadge,
  TinyAvatar: ElAvatar,
  TinyTooltip: ElTooltip,
  TinyPopover: ElPopover,
  TinyDialog: ElDialog,
  TinyDrawer: ElDrawer,
  TinyResult: ElResult,
  TinyEmpty: ElEmpty,
  TinyScrollbar: ElScrollbar,
  ElCard,
  ElRow,
  ElCol,
  ElAvatar,
  ElButton,
  ElDivider,
  ElSpace,
  ElForm,
  ElFormItem,
  ElInput,
  ElSelect,
  ElOption,
  ElSwitch,
  ElRadioGroup,
  ElCheckboxGroup,
  ElDatePicker,
  ElTimePicker,
  ElInputNumber,
  ElRate,
  ElSlider,
  ElColorPicker,
  ElUpload,
  ElTag,
  ElCollapse,
  ElCollapseItem,
  ElTabs,
  ElTabPane,
  ElAlert,
  ElImage,
  ElLink,
  ElTable,
  ElTableColumn,
  ElDescriptions,
  ElDescriptionsItem,
  ElTimeline,
  ElTimelineItem,
  ElSteps,
  ElStep,
  ElProgress,
  ElBadge,
  ElTooltip,
  ElPopover,
  ElDialog,
  ElDrawer,
  ElResult,
  ElEmpty,
  ElScrollbar,
  ElText: 'span' as unknown as Component,
}
